### ISSUE TITLE
Error in the JS

### ISSUE THREAD

**Issue by samuelhgf** [wll8/redoc-try#17]
Hi, I am facing this error in the console when I click in any Try button

<img width="596" alt="Captura de Tela 2021-08-03 às 12 47 10" src="https://user-images.githubusercontent.com/16768378/128046300-7fb00769-7989-4751-8ee3-010785d6c09b.png">

My template file is config like this

```html
<body>
    <div id="redoc-container"></div>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
    <script src="//cdn.jsdelivr.net/gh/wll8/redoc-try@1.3.4/dist/try.js"></script>
    <script>
        initTry({
            openApi: `./openapi.yaml`,
            redocOptions: {
                "untrustedSpec": true,
                    "theme": {
                        "menu": {
                            "backgroundColor": "rgb(195, 241, 211)",
                            "textColor": "rgba(0, 0, 0, 1)",
                        },
                    }
            }
        })
    </script>
</body>
```

**Comment by wll8** [comment]
According to the latest version of redoc, you can replace `redoc@next` with `redoc@2.0.0-rc.55`.

This is caused by incompatibility with the next version flag. Since this flag represents the latest version, which means that the version is uncertain, this issue has not been dealt with before. The next flag was added to this [commit](https://github.com/wll8/redoc-try/commit/bcc36118717d7f679278b42aa1fbd63192c60cef).
