### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ghost** [wll8/redoc-try#18]
This feature is exactly what I am looking for but I am having trouble figuring out how to use it. I cloned the repot and opened `index.html` but the page doesn't load. Does this need to be passed through the redoc-cli tool? Can you please help me with what I am missing?

**Comment by wll8** [comment]
This may be because the cdn protocol referenced by the index.html file in the warehouse is `//`. When you directly double-click the file to open it, the protocol will become `file://` and the cdn cannot be found.

So, Please try to access through the http service protocol, not through the file protocol.

In addition, I have [changed](https://github.com/wll8/redoc-try/commit/dd1c704a7ae156ec7bc19b9df38cedb9044947da) the source code to use the `https://` protocol.

**Comment by ghost** [comment]
@wll8 Thanks! Your demo is now working locally for me and when I update the URL to my swagger spec its also working.
