### ISSUE TITLE
redoc-try causes wrong menu item highlighting when using anchor

### ISSUE THREAD

**Issue by thomasgoldstein** [wll8/redoc-try#20]
To reproduce:
- Go to the online preview: https://wll8.github.io/redoc-try/index.html
- Modify the DOM by inserting an anchor link somewhere at the beginning of the doc, such as `<a href="#operation/placeOrder">test anchor placeOrder</a>` (for example, where it says "This is a sample (...)")
- Click the anchor link you just inserted

Actual result: you scroll to the right endpoint ("Place an order for a pet"), but the menu item highlighted on the left is wrong ("Returns pet inventories by status", ie: the menu item for the route just above the expected one). Manually scrolling down a tiny bit highlights the expected menu item.

Expected result: you scroll to the right endpoint ("Place an order for a pet"), and the menu item highlighted on the left is correct  ("Place an order for a pet").

**Comment by wll8** [comment]
Thank you very much for carefully discovering and describing this problem. After repeated investigations, it was found that this may not be a redoc-try problem.

``` js
Redoc.init('http://petstore.swagger.io/v2/swagger.json', {
  scrollYOffset: 50
})
```
I solved this problem through the `scrollYOffset` configuration, which was [found in the official document](https://github.com/Redocly/redoc/commit/e1e596f44f85d559957115152c945980a2072668) of redoc.

``` html [16]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>redoc try demo</title>
</head>
<body>
  <a href="#operation/placeOrder">test anchor placeOrder</a>
  <div id="redoc-container"></div>
  <script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.48/bundles/redoc.standalone.min.js"> </script>
  <script src="https://cdn.jsdelivr.net/gh/wll8/redoc-try@1.3.4/dist/try.js"></script>
  <script>
    initTry({
      openApi: `https://petstore.swagger.io/v2/swagger.json`, // openApi address
      redocOptions: {scrollYOffset: 50}, // Or the format is an array: `[specOrSpecUrl?, options?, element?, callback?]`
    })
  </script>
</body>
</html>
```

In addition, redoc-try has a slow scrolling function, which happens automatically because of the addition of `swagger-ui-bundle`.

**Comment by thomasgoldstein** [comment]
Thank for your answer!
I'm not sure why the problem only surfaces after adding redoc-try, but setting the scrollYOffset fixed my problem, so that's good. I noticed that the higher the scrollYOffset value, the more the content of the left menu was shifting down (because it adds a top style on the element with the class "menu-content". if you add **scrollYOffset: 50**, then it adds **top: 50px** there), so I had to nullify that with a style override.

I guess we can close this, unless there's a way to tweak redoc-try so that this problem does not happen by default?

**Comment by wll8** [comment]
`unless there's a way to tweak redoc-try so that this problem does not happen by default` This seems difficult **T_T**, and this should be the reason why redoc has this option.

see: [#542 Menu anchors with scrollYOffset don't position correctly first time](https://github.com/Redocly/redoc/issues/542)

**Comment by thomasgoldstein** [comment]
Alright, thanks for the info. Let's close this, then.
