### ISSUE TITLE
Multiple Try it out buttons

### ISSUE THREAD

**Issue by saadshaukat-hello** [wll8/redoc-try#5]
I get multiple try it out buttons instead of one. When clicked, receive the following error.

try.js?v=1:251 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at HTMLButtonElement.<anonymous> (try.js?v=1:251)
    at HTMLButtonElement.dispatch (VM12181 jquery.min.js:3)
    at HTMLButtonElement.q.handle (VM12181 jquery.min.js:3)

**Comment by wll8** [comment]
`Can you give me a code that can see the problem?` Thank you.

Hope to tell me the following information:
- The try.js version or link used
- Your browser and version

In addition, you can try the uncompiled program `https://cdn.jsdelivr.net/gh/wll8/redoc-try/try.js` to get a clearer error location.

In addition, do you mean multiple buttons under one API?

**Comment by akalineskou** [comment]
I had the same issue, and it was because redoc suggests you initialize it using
`<redoc spec-url="url/doc.json"></redoc>` but if you add the id `redoc-container` to that element, it will get initialized 2 times (thus the regex which finds the selector wont work)

If you just add `<div id="redoc-container"></div>` and delete `<redoc>` it works for me.
This should be mentioned in the docs IMO since this library will initialize Redoc for you and not just iteself.

**Comment by wll8** [comment]
Thank you for your feedback. I have added this hint in the readme.
And released [new features](https://github.com/wll8/redoc-try/commit/7b146f492ec3482e9b4993f8eaeb6edb2f66312d) and [tools](https://github.com/wll8/mockm), welcome to use.
